server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: qualunque path che non è un file statico esistente ricade su index.html
    # cosi' react-router-dom gestisce il routing lato client.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
